name: Lint & Format

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
      
      - name: Instalar Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Checar formatação (rustfmt)
        run: cargo fmt -- --check
      
      - name: Rodar Clippy (linter)
        run: cargo clippy -- -D warnings
