name: "Validate PRs"

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize

permissions:
  pull-requests: write

jobs:
  validate-pr:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        id: validate_pr_title
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: marocchino/sticky-pull-request-comment@v2
        if: always() && (steps.validate_pr_title.outputs.error_message != null)
        with:
          header: pr-title-lint-error
          message: |
            Olá! 👋🏼

            É obrigatório que o título do PR siga o [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/) e parece que o título do seu PR precisa ser ajustado.

            Detalhes:

            ```
            ${{ steps.validate_pr_title.outputs.error_message }}
            ```

      # Remove o comentário antigo quando o título do PR for atualizado
      - if: ${{ steps.validate_pr_title.outputs.error_message == null }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr-title-lint-error
          delete: true       